tests/snapshots/all__lp_attributes2__0.txt
tests/snapshots/all__lp_attributes4__0.txt
tests/snapshots/all__lp_matrix0__0.txt
tests/snapshots/all__lp_matrix10__0.txt
tests/snapshots/all__lp_matrix11__0.txt
tests/snapshots/all__lp_matrix1__0.txt
tests/snapshots/all__lp_matrix2__0.txt
tests/snapshots/all__lp_matrix3__0.txt
tests/snapshots/all__lp_matrix4__0.txt
tests/snapshots/all__lp_matrix5__0.txt
tests/snapshots/all__lp_matrix6__0.txt
tests/snapshots/all__lp_matrix7__0.txt
tests/snapshots/all__lp_matrix8__0.txt
tests/snapshots/all__lp_matrix9__0.txt
tests/snapshots/all__lp_matrix_quadratic2__0.txt
tests/snapshots/all__lp_matrix_quadratic3__0.txt
tests/snapshots/all__lp_scalar_linear0__0.txt
tests/snapshots/all__lp_scalar_linear10__0.txt
tests/snapshots/all__lp_scalar_linear11__0.txt
tests/snapshots/all__lp_scalar_linear12__0.txt
tests/snapshots/all__lp_scalar_linear1__0.txt
tests/snapshots/all__lp_scalar_linear2__0.txt
tests/snapshots/all__lp_scalar_linear3__0.txt
tests/snapshots/all__lp_scalar_linear4__0.txt
tests/snapshots/all__lp_scalar_linear5__0.txt
tests/snapshots/all__lp_scalar_linear6__0.txt
tests/snapshots/all__lp_scalar_linear7__0.txt
tests/snapshots/all__lp_scalar_linear8__0.txt
tests/snapshots/all__lp_scalar_linear9__0.txt
tests/test_problems.py

Without this, adding a test case will increase the constraint ids for all following test problems, even those in other groups.

Reset constraints ids between test groups

---

src/cvxpy_gurobi/__init__.py
tests/snapshots/all__lp_indexing0__0.txt
tests/snapshots/all__lp_indexing10__0.txt
tests/snapshots/all__lp_indexing11__0.txt
tests/snapshots/all__lp_indexing12__0.txt
tests/snapshots/all__lp_indexing13__0.txt
tests/snapshots/all__lp_indexing14__0.txt
tests/snapshots/all__lp_indexing15__0.txt
tests/snapshots/all__lp_indexing1__0.txt
tests/snapshots/all__lp_indexing2__0.txt
tests/snapshots/all__lp_indexing3__0.txt
tests/snapshots/all__lp_indexing4__0.txt
tests/snapshots/all__lp_indexing5__0.txt
tests/snapshots/all__lp_indexing6__0.txt
tests/snapshots/all__lp_indexing7__0.txt
tests/snapshots/all__lp_indexing8__0.txt
tests/snapshots/all__lp_indexing9__0.txt
tests/test_problems.py

Expressions such as `x[0]`.
By the way, fixed a bug in matrix variable names and added more information to "unsupported" error messages.

Add support for expression indexing

---

pyproject.toml

(Test)PyPI does not accept local version specifiers.
```
Uploading cvxpy_gurobi-0.1.dev18+g7d98973-py3-none-any.whl
WARNING  Error during upload. Retry with the --verbose option for more details. 
ERROR    HTTPError: 400 Bad Request from https://test.pypi.org/legacy/          
The use of local versions in <Version('0.1.dev18+g7d98973')> is not    
allowed. See https://packaging.python.org/specifications/core-metadata 
for more information.
```
Also, some metadata was wrong in the built distribution.

Remove local version specifier

---

README.md
src/cvxpy_gurobi/__init__.py
tests/test_all.py
tests/test_api.py

The API is now much closer to CVXPY's. Using `cvxpy-gurobi` is now as simple as changing:
```diff
- problem.solve(solver=cp.GUROBI, QCPDual=True)
+ problem.solve(method=GUROBI_TRANSLATION, QCPDual=True)
```
or without registration:
```diff
- problem.solve(solver=cp.GUROBI, QCPDual=True)
+ cvxpy_gurobi.solve(problem, QCPDual=True)
```
To keep things simple and make it easier to change in the future, a few functions were removed from the public API, and the README was updated to account for these changes.

Remove kwargs on solver registration

---

src/cvxpy_gurobi/__init__.py
tests/test_atoms.py

As opposed to having a specific step before translation. It helps to make variables similar to other nodes. This will be necessary to support more complex expressions #23 as some expressions' translation may require additional variables.
Removing the `map_variables` step revealed that separating the objective and constraint translaters was unnecessary, as now any translation method may add variables/constraints to the model.
One downside is that the translation can no longer be run "model-free" to generate modle-agnostic expressions. This impression was wrong however as any variable used in these expressions was linked to a Gurobi model anyway.

Create Gurobi variables during translation

---

CHANGELOG.md
pyproject.toml
src/cvxpy_gurobi/__init__.py
tests/snapshots/all__lp_genexpr_matrix0__0.txt
tests/snapshots/all__lp_genexpr_matrix1__0.txt
tests/snapshots/all__lp_genexpr_matrix2__0.txt
tests/snapshots/all__lp_genexpr_matrix3__0.txt
tests/snapshots/all__lp_genexpr_matrix4__0.txt
tests/snapshots/all__lp_genexpr_matrix5__0.txt
tests/snapshots/all__lp_genexpr_scalar0__0.txt
tests/snapshots/all__lp_genexpr_scalar1__0.txt
tests/snapshots/all__lp_genexpr_scalar2__0.txt
tests/snapshots/all__lp_genexpr_scalar3__0.txt
tests/snapshots/all__lp_genexpr_vector0__0.txt
tests/snapshots/all__lp_genexpr_vector1__0.txt
tests/snapshots/all__lp_genexpr_vector2__0.txt
tests/snapshots/all__lp_genexpr_vector3__0.txt
tests/snapshots/all__lp_genexpr_vector4__0.txt
tests/snapshots/all__lp_genexpr_vector5__0.txt
tests/test_problems.py

Part of #23
The absolute value is now handled in the scalar, vector and matrix cases. Auxiliary variables are added to the model to represent the absolute values. 
Extracted from #26 as there were too many changes at once 😅
It helped to reveal some issues when using matrices as the shape wasn't kept after translation. Also, constant absolute values are evaluated directly instead of generating variables.

Support `abs` generalized expressions

---

pyproject.toml
tests/snapshots/all__lp_matrix10__0.txt
tests/snapshots/all__lp_matrix11__0.txt
tests/snapshots/all__lp_matrix9__0.txt
tests/snapshots/all__lp_matrix_quadratic5__0.txt

The Gurobi interface in CVXPY was fixed for NumPy v2 in https://github.com/cvxpy/cvxpy/pull/2484, released in v1.5.3.
It seems the formatting of sparse matrices changed, something to do with the interaction between SciPy and NumPy v2. Not quite sure if this change was intended or not 🤷

Update fixtures for CVXPY v1.5.3 and NumPy v2

---

src/cvxpy_gurobi/__init__.py
tests/snapshots/all__lp_genexpr_norm1_0__0.txt
tests/snapshots/all__lp_genexpr_norm1_10__0.txt
tests/snapshots/all__lp_genexpr_norm1_11__0.txt
tests/snapshots/all__lp_genexpr_norm1_12__0.txt
tests/snapshots/all__lp_genexpr_norm1_13__0.txt
tests/snapshots/all__lp_genexpr_norm1_14__0.txt
tests/snapshots/all__lp_genexpr_norm1_15__0.txt
tests/snapshots/all__lp_genexpr_norm1_1__0.txt
tests/snapshots/all__lp_genexpr_norm1_2__0.txt
tests/snapshots/all__lp_genexpr_norm1_3__0.txt
tests/snapshots/all__lp_genexpr_norm1_4__0.txt
tests/snapshots/all__lp_genexpr_norm1_5__0.txt
tests/snapshots/all__lp_genexpr_norm1_6__0.txt
tests/snapshots/all__lp_genexpr_norm1_7__0.txt
tests/snapshots/all__lp_genexpr_norm1_8__0.txt
tests/snapshots/all__lp_genexpr_norm1_9__0.txt
tests/snapshots/all__lp_genexpr_norm2_0__0.txt
tests/snapshots/all__lp_genexpr_norm2_1__0.txt
tests/test_problems.py

Gurobi only handles vector norms, so we have to ensure we always use 1D arrays when forwarding to `numpy` and/or `cvxpy` since they also have matrix norms.
Part of #23

Support norm1 atom

---

src/cvxpy_gurobi/translation.py
tests/snapshots/all__lp_hstack0__0.txt
tests/snapshots/all__lp_hstack10__0.txt
tests/snapshots/all__lp_hstack11__0.txt
tests/snapshots/all__lp_hstack12__0.txt
tests/snapshots/all__lp_hstack13__0.txt
tests/snapshots/all__lp_hstack14__0.txt
tests/snapshots/all__lp_hstack15__0.txt
tests/snapshots/all__lp_hstack1__0.txt
tests/snapshots/all__lp_hstack2__0.txt
tests/snapshots/all__lp_hstack3__0.txt
tests/snapshots/all__lp_hstack4__0.txt
tests/snapshots/all__lp_hstack5__0.txt
tests/snapshots/all__lp_hstack6__0.txt
tests/snapshots/all__lp_hstack7__0.txt
tests/snapshots/all__lp_hstack8__0.txt
tests/snapshots/all__lp_hstack9__0.txt
tests/snapshots/all__lp_reshape28__0.txt
tests/snapshots/all__lp_vstack0__0.txt
tests/snapshots/all__lp_vstack1__0.txt
tests/snapshots/all__lp_vstack2__0.txt
tests/snapshots/all__lp_vstack3__0.txt
tests/snapshots/all__lp_vstack4__0.txt
tests/snapshots/all__lp_vstack5__0.txt
tests/snapshots/all__lp_vstack6__0.txt
tests/snapshots/all__lp_vstack7__0.txt
tests/snapshots/all__lp_vstack8__0.txt
tests/snapshots/all__lp_vstack9__0.txt
tests/test_problems.py

Mostly a wrapper around a series of reshapes, as the stacking itself is then handled by Gurobi.
The tests have some differences between H- and V-stack because both aren't implemented in the same way. `cp.hstack` will reshape scalars into (1,)-shaped expressions, but `cp.vstack` does not so it can't be called with scalars.
Resolves #32

Support `hstack` and `vstack` atoms

---

pyproject.toml
src/cvxpy_gurobi/translation.py
tests/test_problems.py

This PR updates the test matrix to get all tests passing. Noticeable changes:
- `gp.{h,v}stack` was added in version 11, so skip the corresponding tests and raise an error during translation,
- older versions' tests are run first as they are the most likely to have failures,
- removed some version restrictions on numpy since the issues were fixed in recent versions,
- `pytest-xdist` is now installed in test environments, the number of tests grew large enough that the time spent instantiating workers is smaller than the gain due to parallelization.
There is a weird issue with `cvxpy==1.4`, not sure what it's about yet, so it's not tested.

Stack is not available on `gurobipy<11`

---

src/cvxpy_gurobi/translation.py
tests/snapshots/all__lp_sum_scalar0__0.txt
tests/snapshots/all__lp_sum_scalar1__0.txt
tests/snapshots/all__lp_sum_scalar2__0.txt
tests/snapshots/all__lp_sum_scalar3__0.txt
tests/snapshots/all__lp_sum_scalar4__0.txt
tests/snapshots/all__lp_sum_scalar5__0.txt
tests/test_problems.py

`cvxpy` does not need special handling for `cp.sum(x)` where `x` is a scalar expression, but once translated into `gurobipy` objects, scalar expressions do not have the `.sum` method that matrixapi objects have. So in the scalar case, we simply return the expression to sum.

Fix handling of sum of scalar expression

---

src/cvxpy_gurobi/translation.py
tests/snapshots/all__lp_genexpr_min_max11__0.txt
tests/snapshots/all__lp_genexpr_min_max15__0.txt
tests/snapshots/all__lp_genexpr_min_max3__0.txt
tests/snapshots/all__lp_genexpr_min_max7__0.txt

Fixes #47 by forcing the `gp.min` and `gp.max` arguments to be scalars. I added a new parameter to `translate_into_variable` to explicitly ask for a scalar variable. Before this change, we tried to create a scalar variable when possible, but now it's explicit.
Now the responsabilities of `translate_into_variable` and `translate_into_scalar` are a little mixed, so it might be worth revisiting/merging them in the future.
The snapshot differences come from the change in the `_min_max` function to not create an auxilliary variable if the argument is already scalar. It makes a nicer looking problem, but we lose track of the `min`/`max` completely, so I'm still not 100% sure it should stay this way.

Ensure `minimum`/`maximum` arguments are scalars

---

CHANGELOG.md
src/cvxpy_gurobi/translation.py
tests/snapshots/all__lp_quad_form0__0.txt
tests/snapshots/all__lp_quad_form1__0.txt
tests/snapshots/all__lp_quad_form2__0.txt
tests/snapshots/all__lp_quad_form3__0.txt
tests/test_problems.py

Resolves #33.
Nothing special, it just works. Note that I didn't test with complex-valued variables, but I'm not sure Gurobi handles them anyway.

Add support for `quad_form`

---

pyproject.toml

It expired on 2024-10-28, so none of the tests are passing with that version.
Bumping to v11 unearth another issue with `vstack` (which is skipped on older versions of `gurobipy`), this time related to the version of `cvxpy` used in the _oldest_ tests. So I also bumped the minimum tested version of `cvxpy` to 1.2.0 (which released cvxpy/cvxpy#1339), and switched to `cvxpy-base`.
The testing scope of `gurobipy` is now limited to v11, but v12 should be out _soon_ anyway so it won't be the newest version anymore.

Avoid testing on `gurobipy` 10 since the license expired

---

CHANGELOG.md
README.md
src/cvxpy_gurobi/translation.py
tests/snapshots/all__lp_nonlinear_exp0__0.txt
tests/snapshots/all__lp_nonlinear_exp1__0.txt
tests/snapshots/all__lp_nonlinear_exp2__0.txt
tests/snapshots/all__lp_nonlinear_exp3__0.txt
tests/snapshots/all__lp_nonlinear_exp4__0.txt
tests/snapshots/all__lp_nonlinear_exp5__0.txt
tests/snapshots/all__lp_nonlinear_exp6__0.txt
tests/snapshots/all__lp_nonlinear_exp7__0.txt
tests/snapshots/all__lp_nonlinear_exp8__0.txt
tests/test_all.py
tests/test_problems.py

This is the first feature the cvxpy interface doesn't support, even though it can be expressed in cvxpy's DSL!

Add support for `cp.exp` through non-linear expressions

---

CHANGELOG.md
src/cvxpy_gurobi/translation.py
tests/snapshots/all__lp_nonlinear_log0__0.txt
tests/snapshots/all__lp_nonlinear_log1__0.txt
tests/snapshots/all__lp_nonlinear_log2__0.txt
tests/snapshots/all__lp_nonlinear_log3__0.txt
tests/snapshots/all__lp_nonlinear_log4__0.txt
tests/snapshots/all__lp_nonlinear_log5__0.txt
tests/snapshots/all__lp_nonlinear_log6__0.txt
tests/snapshots/all__lp_nonlinear_log7__0.txt
tests/snapshots/all__lp_nonlinear_log8__0.txt
tests/test_problems.py

Exactly the same as for `exp`.
Closes #83

Add support for `log` and `log1p`

---

.pre-commit-config.yaml
pyproject.toml
src/cvxpy_gurobi/interface.py
src/cvxpy_gurobi/translation.py
tests/test_problems.py

There is a warning when it is not given explicitly. There is also one for `vec`, unfortunately the `reshape` argument was added more recently and didn't exist in 1.2.0.
I also did a few cosmetic changes to the pytest configuration.

Specify order for reshape atom

---

pyproject.toml
src/cvxpy_translation/gurobi/interface.py
src/cvxpy_translation/gurobi/translation.py
tests/test_atoms.py

Only the D10x rules are annoying, so enable the rest.
It's really just an excuse to test the deplyment to Test PyPI works :shushing_face:

Enable some ruff rules for docstrings

---

src/cvxpy_translation/scip/interface.py
tests/snapshots/scip/all__lp_quadratic13__0.txt
tests/snapshots/scip/all__lp_quadratic14__0.txt
tests/snapshots/scip/all__lp_quadratic15__0.txt
tests/snapshots/scip/all__lp_quadratic16__0.txt
tests/snapshots/scip/all__lp_quadratic17__0.txt
tests/snapshots/scip/all__lp_quadratic18__0.txt
tests/snapshots/scip/all__lp_quadratic19__0.txt
tests/snapshots/scip/all__lp_quadratic20__0.txt
tests/snapshots/scip/all__lp_quadratic21__0.txt
tests/snapshots/scip/all__lp_quadratic22__0.txt
tests/snapshots/scip/all__lp_quadratic23__0.txt
tests/snapshots/scip/all__lp_quadratic24__0.txt
tests/snapshots/scip/all__lp_quadratic25__0.txt
tests/snapshots/scip/all__lp_scalar_linear13__0.txt
tests/snapshots/scip/all__lp_scalar_linear14__0.txt
tests/snapshots/scip/all__lp_scalar_linear15__0.txt
tests/snapshots/scip/all__lp_scalar_linear16__0.txt
tests/snapshots/scip/all__lp_scalar_linear17__0.txt
tests/snapshots/scip/all__lp_scalar_linear18__0.txt
tests/snapshots/scip/all__lp_scalar_linear19__0.txt
tests/snapshots/scip/all__lp_scalar_linear20__0.txt
tests/snapshots/scip/all__lp_scalar_linear21__0.txt
tests/snapshots/scip/all__lp_scalar_linear22__0.txt
tests/snapshots/scip/all__lp_scalar_linear23__0.txt
tests/snapshots/scip/all__lp_scalar_linear24__0.txt
tests/snapshots/scip/all__lp_scalar_linear25__0.txt
tests/test_all.py
tests/test_problems.py

To get better precision in the results, the tolerances had to be reduced on the solver.

Enable scalar linear and quadratic test cases for SCIP

---

src/cvxpy_translation/scip/translation.py
tests/snapshots/gurobi/all__lp_sum_axis0__0.txt
tests/snapshots/gurobi/all__lp_sum_axis1__0.txt
tests/snapshots/gurobi/all__lp_sum_axis3__0.txt
tests/snapshots/scip/all__lp_sum_axis4__0.txt
tests/snapshots/scip/all__lp_sum_axis5__0.txt
tests/snapshots/scip/all__lp_sum_axis6__0.txt
tests/snapshots/scip/all__lp_sum_axis7__0.txt
tests/test_all.py
tests/test_problems.py

1. The axis argument does not work on SCIP variables, so the axis sum is implemented manually
2. The tests did not have a unique solution, so I added coefficients for each variable
3. I added a test with a negative index, it turns out CVXPY just recently added support for that

Support sum with axis for SCIP

---

src/cvxpy_translation/scip/translation.py
tests/snapshots/scip/lp__hstack_00.txt
tests/snapshots/scip/lp__hstack_01.txt
tests/snapshots/scip/lp__hstack_02.txt
tests/snapshots/scip/lp__hstack_03.txt
tests/snapshots/scip/lp__hstack_04.txt
tests/snapshots/scip/lp__hstack_05.txt
tests/snapshots/scip/lp__hstack_06.txt
tests/snapshots/scip/lp__hstack_07.txt
tests/snapshots/scip/lp__hstack_08.txt
tests/snapshots/scip/lp__hstack_09.txt
tests/snapshots/scip/lp__hstack_10.txt
tests/snapshots/scip/lp__hstack_11.txt
tests/snapshots/scip/lp__hstack_12.txt
tests/snapshots/scip/lp__hstack_13.txt
tests/snapshots/scip/lp__hstack_14.txt
tests/snapshots/scip/lp__hstack_15.txt
tests/snapshots/scip/lp__quad_form_stack_00.txt
tests/snapshots/scip/lp__vstack_00.txt
tests/snapshots/scip/lp__vstack_01.txt
tests/snapshots/scip/lp__vstack_02.txt
tests/snapshots/scip/lp__vstack_03.txt
tests/snapshots/scip/lp__vstack_04.txt
tests/snapshots/scip/lp__vstack_05.txt
tests/snapshots/scip/lp__vstack_06.txt
tests/snapshots/scip/lp__vstack_07.txt
tests/snapshots/scip/lp__vstack_08.txt
tests/snapshots/scip/lp__vstack_09.txt
tests/test_problems.py

Since the SCIP matrix API just uses NumPy arrays, it is really easy. Though the result of the stack is not a SCIP object, it's a plain array. It doesn't seem to cause issues when computing, but there might be some edge cases where it fails?
Oh and this greatly improved the `quad_form_stack` test case as we don't need the auxiliary variable anymore :tada:

Support h- and v-stack with SCIP

---

src/cvxpy_translation/__init__.py
src/cvxpy_translation/exceptions.py
src/cvxpy_translation/gurobi/translation.py
src/cvxpy_translation/scip/__init__.py
src/cvxpy_translation/scip/translation.py
tests/snapshots/scip/lp__scalar_stack_00.txt
tests/snapshots/scip/lp__scalar_stack_01.txt
tests/test_atoms.py
tests/test_problems.py

Move the base exceptions to the library root, which makes it possible to catch exceptions no matter which solver/translater is used.
This enables us to unblock the tests for invalid cases for both SCIP and Gurobi.
There is something weird going on with gurobipy's `hstack`, not sure why. There's no issue with `vstack`. But for now we just skip both on Gurobi.

Use common exception hierarchy

---

src/cvxpy_translation/__init__.py
src/cvxpy_translation/gurobi/interface.py
src/cvxpy_translation/interface.py
src/cvxpy_translation/scip/interface.py
src/cvxpy_translation/scip/translation.py

Bumps coverage from 85% to 92%. Most of the remaining missed lines are due to version-dependent code.
I also removed the fill_model function from the global interface as it was not exposed from Gurobi previously.

Remove unused methods from SCIP implementation

---

tests/conftest.py
tests/test_all.py

Since the snapshot overhaul in #145, insta would delete all snapshots at the start of the test session and then fail because they are missing. The solution was to delete all snapshots, and have insta create them from scratch.
It turns this is due to the way snapshots are now named. It gives the false impression that all tests in a group belong to the same test case, so when insta does not detect more than 1 test in the case, it assumes all the others are outdated and should be removed.
This is annoying because I like the naming scheme. Since we don't remove snapshots that often, I fix this problem by having insta not detect outdated snapshots. It means that to remove an outdated snapshots, we still need to delete all of them and rerun, but that doesn't happen too much.
The snapshot setup …

Prevent insta from deleting all snapshots on startup

---

.github/workflows/ci.yml
CHANGELOG.md
pyproject.toml
src/cvxpy_translation/gurobi/interface.py
src/cvxpy_translation/gurobi/translation.py
src/cvxpy_translation/interface.py
src/cvxpy_translation/scip/interface.py
src/cvxpy_translation/scip/translation.py
tests/test_all.py
tests/test_problems.py

It's about time, even though the only gain we get is newer test dependencies...

Drop support for Python 3.8

---

CHANGELOG.md
pyproject.toml
src/cvxpy_translation/gurobi/translation.py
src/cvxpy_translation/scip/translation.py
tests/snapshots/gurobi/lp__reshape_30.txt
tests/snapshots/gurobi/lp__reshape_31.txt
tests/snapshots/scip/lp__reshape_30.txt
tests/snapshots/scip/lp__reshape_31.txt
tests/test_problems.py

This was due to the reshape translation checking for constants instead of working with any constant value, such as parameters.

Remove auxilliary variable when reshaping parameters

---

CHANGELOG.md
src/cvxpy_translation/exceptions.py
src/cvxpy_translation/gurobi/translation.py
src/cvxpy_translation/scip/translation.py
tests/test_atoms.py
tests/test_problems.py

Closes #130 
Closes #168 
We only allow a limited set of attributes and error on anything else.
The tests are a little subtle because we have to avoid using unsupported atoms to ensure we hit the attribute-related errors.

Error on unsupported leaf attributes

---

pyproject.toml

Since `cvxpy` is not listed as a dependency, this is the only way to communicate the supported versions.

Add extras for cvxpy and cvxpy-base

---

CHANGELOG.md
src/cvxpy_translation/exceptions.py
src/cvxpy_translation/gurobi/translation.py
src/cvxpy_translation/scip/translation.py
tests/test_problems.py

Variables can be set as boolean or integer only on some indexes. This is not supported by Gurobi nor SCIP, so when we detect this case, we should error out.

Error on partially boolean or integer variables

---

CHANGELOG.md
src/cvxpy_translation/scip/interface.py
tests/test_backfill.py

We have to work around the status mapping on CVXPY to ensure we assign the correct status based on the SCIP model, and then we have to trick CVXPY into thinking it's another status.
A real mess, hopefully the tests will detect if anything changes.
Fixes #199.

Fix SCIP when user limit is hit
